title: "My Jekyll Site"
description: "A simple Jekyll site"
baseurl: "/SkillStart-Hub"
url: "https://ineza-agape.github.io/SkillStart-Hub/"
exclude:
  - node_modules/
  - servers/node_modules/
  - .git/
  - .github/
  - "*.md"
  - README.md

theme: jekyll-theme-minimal