[build]
  command = "npm install && npm install typescript && npx tsc"
  publish = "templates"
  functions = "servers/dist"

[context.production.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"